### ISSUE TITLE
export to txt

### ISSUE THREAD

**Issue by diepnt90** [dieterds/bytubed_chrome#3]
Hi
could you deploy a function that export all downloading link into txt file ?

**Comment by dieterds** [comment]
As its still not possible to interact with local filesystem in chrome extensions (afaik), i can only offer the following atm:
1. An option to create either html or text
   or  option to create html and additional as text
   Example: 
   only links like
   "http://youtubelink.com/video?OJCKA345J
   http://youtubelink.com/video?ORHA246A"
   or links with title like
   "The Level S01E01;http://youtubelink.com/video?OJCKA345J
   The Level S01E02;http://youtubelink.com/video?ORHA246A"
2. A button on the created html-page, which gives only the links on a new page (maybe copied so clipboard).

**Comment by diepnt90** [comment]
Now, this option(2) is available or next version will be released ?

**Comment by dieterds** [comment]
I submitted the new code. there is now a button on the videolinkpage, which copies all videourls to the clipboard.

**Comment by diepnt90** [comment]
Dear ,

thanks. where i can get this extension. i checked the release page but not found
https://github.com/dieterds/bytubed_chrome

**Comment by dieterds** [comment]
sorry, i'm not that fast. i created a new release.

**Comment by diepnt90** [comment]
when you release it. pleae inform me. thanks so much for your help.

**Comment by dieterds** [comment]
its available on the release page

**Comment by diepnt90** [comment]
OH, it works. Thanks so much !

**Comment by dieterds** [comment]
ok, nice so hear. 
if you have other wishes, you can create another issue.
