### ISSUE TITLE
Videoplayback.txt

### ISSUE THREAD

**Issue by amitchoudhary13** [dieterds/bytubed_chrome#4]
while running it generate the download link but . on downloading it generates an error Videoplayback.txt forbidden.

and there is error thrown in extension also

> chrome://downloads/ skipped!

> popup.js:567 (anonymous function)

`                if (tab.url.indexOf("chrome") === 0) { console.warn(tab.url + ' skipped!'); continue }
`

**Comment by dieterds** [comment]
Bug solved with 1.0.3
